INSERT INTO numberscale(Base_Illion_Short, Base_Illion_long, Base, Exponent, Short_Scale_Name, Long_Scale_Name_1, Long_Scale_Name_2, SI_Symbol)
VALUES 
	(1,1,10,6,"Million","Million","Million","M"),
    (2,1,10,9,"Billion","Thousand Million","Milliard","B"),
    (3,2,10,12,"Trillion","Billion","Billion","T"),
    (4,2,10,15,"Quadrillion","Thousand Billion","Billiard","q"),
    (5,3,10,18,"Quintillion","Trillion","Trillion","Q"),
    (6,3,10,21,"Sextillion","Thousand Trillion","Trilliard","s"),
    (7,4,10,24,"Septillion","Quadrillion","Quadrillion","S"),
    (8,4,10,27,"Octillion","Thousand Quadrillion","Quadrilliard","o"),
    (9,5,10,30,"Nonillion", "Quintillion", "Quintillion", "N"),
    (10,5,10,33,"Decillion","Thousand quintillion","Quintilliard","d"),
    (11,6,10,36,"Undecillion","Sextillion","Sextillion","U"),
    (12,6,10,39,"Duodecillion","Thousand sextillion","Sextilliard","D"),
    (13,7,10,42,"Tredecillion","Septillion","Septillion","Td"),
    (14,7,10,45,"Quattuordecillion","Thousand septillion","Septilliard","qd"),
    (15,8,10,48,"Quindecillion","Octillion","Octillion","Qd"),
    (16,8,10,51,"Sedecillion","Thousand octillion","Octilliard","sd"),
    (17,9,10,54,"Septendecillion","Nonillion","Nonillion","Sd"),
    (18,9,10,57,"Octodecillion","Thousand nonillion","Nonilliard","Od"),
    (19,10,10,60,"Novendecillion","Decillion","Decillion","Nd"),
    (20,10,10,63,"Vigintillion","Thousand decillion","Decilliard","V"),
    (21,11,10,66,"Unvigintillion","Undecillion","Undecillion","uV"),
    (22,11,10,69,"Duovigintillion","Thousand undecillion","Undecilliard","dV"),
    (23,12,10,72,"Tresvigintillion","Duodecillion","Duodecillion","tV"),
    (24,12,10,75,"Quattuorvigintillion","Thousand duodecillion","Duodecilliard","qV"),
    (25,13,10,78,"Quinvigintillion","Tredecillion","Tredecillion","QV"),
    (26,13,10,81,"Sesvigintillion","Thousand tredecillion","Tredecilliard","sV"),
    (27,14,10,84,"Septemvigintillion","Quattuordecillion","Quattuordecillion","SV"),
    (28,14,10,87,"Octovigintillion","Thousand quattuordecillion","Quattuordecilliard","OV"),
    (29,15,10,90,"Novemvigintillion","Quindecillion","Quindecillion","NV"),
    (30,15,10,93,"Trigintillion","Thousand quindecillion","Quindecilliard","tT")